In [26]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import random

In [2]:
x = tf.constant([[1, 2], [3, 4]])

In [3]:
print(x)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [4]:
x.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [8]:
b = tf.Variable([[1.0], [2.0]])

In [9]:
with tf.GradientTape() as tape:
    k = tf.linalg.matmul(b, tf.transpose(b))
    dk_db = tape.gradient(k, b)
    print(dk_db)

tf.Tensor(
[[6.]
 [6.]], shape=(2, 1), dtype=float32)


In [10]:
print(tf.transpose(b))

tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)


# How does the above make sense?

In [11]:
# Attempting to make a neural network run with Keras
# Again, we use just one set of values. 

In [12]:
import numpy as np

In [20]:
x = np.array([[[1, 2, 3], [3, 4, 3]], [[1, 2, 3], [3, 4, 3]], [[1, 2, 3], [3, 4, 3]]])

In [21]:
x.shape

(3, 2, 3)

## Questions
1. Does training happen multiple datapoints at a time, or just one?
2. What is a layer shape?
3. GradientTape - how are higher order gradients calculated?

In [4]:
from tensorflow.keras import layers

In [6]:
layer = layers.Dense(32, activation = 'relu')

In [8]:
class Linear(layers.Layer):
    def __init__(self, units = 32):
        super(Linear, self).__init__()
        self.units = units
    
    def build(self, input_shape):
        self.w = self.add_weight(
            shape = (input_shape[-1], self.units),
            initializer = "random_normal", 
            trainable = True
        )
        
        self.b = self.add_weight(
            shape = (self.units, ),
            initializer = "random_normal",
            trainable = True
        )
    
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b
    

In [20]:
a = np.array([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0]])

In [15]:
b = np.array([5, 5])

In [16]:
a+b


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [21]:
linear_layer = Linear(4)

In [22]:
y = linear_layer(a)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [23]:
y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.04388   , -0.22998697,  0.20792815, -0.07843678],
       [ 0.10285286, -0.38874537,  0.34910026, -0.19109249]],
      dtype=float32)>

In [24]:
y.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.04388   , -0.22998697,  0.20792815, -0.07843678],
       [ 0.10285286, -0.38874537,  0.34910026, -0.19109249]],
      dtype=float32)>>

## Okay, I attempt to use the above linear layer to learn a function

In [46]:
X = np.array([[random.random() for i in range(10)] for j in range(100)])

In [47]:
Y = np.array([[X[i][0]/2] for i in range(100)])

In [48]:
X


array([[2.16516275e-01, 4.52325155e-01, 5.32777127e-01, 7.22560264e-01,
        9.56288209e-01, 7.03761984e-01, 9.58564533e-01, 6.59447714e-01,
        2.84955134e-02, 1.16175147e-01],
       [7.26017653e-01, 3.50983721e-02, 8.15696602e-01, 4.59869560e-01,
        8.23229475e-01, 9.22358909e-01, 4.17603371e-02, 2.04199559e-01,
        2.30529745e-01, 3.03476404e-01],
       [8.46697650e-01, 5.24913284e-01, 2.60050645e-01, 2.06690676e-01,
        7.43119534e-01, 8.04232597e-01, 5.44110959e-01, 6.73325241e-02,
        8.22001588e-02, 4.28605801e-01],
       [3.89190080e-01, 3.61369545e-01, 6.07727728e-01, 6.87158215e-01,
        5.88220117e-02, 2.02409358e-01, 4.65979095e-01, 5.93445941e-01,
        6.72085876e-01, 6.73879662e-01],
       [3.86457209e-01, 2.74943189e-01, 6.57735149e-01, 7.50114510e-01,
        3.59624798e-01, 8.72615156e-01, 1.47206923e-01, 3.91243853e-02,
        7.97298242e-01, 7.58520632e-01],
       [7.42243237e-01, 6.03738041e-01, 9.09159803e-01, 7.19831311e-01,
   

In [49]:
Y

array([[0.10825814],
       [0.36300883],
       [0.42334883],
       [0.19459504],
       [0.1932286 ],
       [0.37112162],
       [0.36602734],
       [0.09264161],
       [0.32672682],
       [0.11622543],
       [0.26201571],
       [0.41516435],
       [0.39701901],
       [0.00590674],
       [0.25268601],
       [0.22111625],
       [0.49826189],
       [0.40415527],
       [0.12010963],
       [0.37264827],
       [0.05285096],
       [0.28066651],
       [0.20251852],
       [0.32482347],
       [0.02471794],
       [0.25218933],
       [0.41335683],
       [0.40251602],
       [0.45863035],
       [0.15342039],
       [0.22480193],
       [0.26873785],
       [0.02329902],
       [0.38925232],
       [0.49284091],
       [0.2529094 ],
       [0.2808879 ],
       [0.06658327],
       [0.31458   ],
       [0.36404116],
       [0.00209299],
       [0.45642654],
       [0.11521597],
       [0.33643202],
       [0.27390599],
       [0.1990017 ],
       [0.21203842],
       [0.215

# The network!

In [70]:
ll = Linear(1)
loss_fn = tf.keras.losses.MeanSquaredError()
optimizer = tf.keras.optimizers.SGD(learning_rate = 1e-3)

In [73]:
for i in range(500):
    with tf.GradientTape() as tape:
        logits = ll(X)
        loss = loss_fn(Y, logits)
        print(logits.shape)
        print(Y.shape)
        print(loss)
        gradients = tape.gradient(loss, ll.trainable_weights)
        print(gradients)
        optimizer.apply_gradients(zip(gradients, ll.trainable_weights))
        print(str(i+1)+":"+str(loss))
    

    

(100, 1)
(100, 1)
tf.Tensor(0.019290859, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.08415522],
       [-0.00621042],
       [-0.00124417],
       [-0.02202741],
       [-0.00690133],
       [ 0.00760239],
       [ 0.00463357],
       [ 0.02087462],
       [-0.00054518],
       [ 0.00351513]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.01047547], dtype=float32)>]
1:tf.Tensor(0.019290859, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.01928257, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.08407736],
       [-0.00615157],
       [-0.00118145],
       [-0.02196537],
       [-0.00684378],
       [ 0.00765987],
       [ 0.00469663],
       [ 0.02092307],
       [-0.00048815],
       [ 0.00357307]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.01036322], dtype=float32)>]
2:tf.Tensor(0.01928257, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(

(100, 1)
(100, 1)
tf.Tensor(0.019072143, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.08221223],
       [-0.00477029],
       [ 0.00028964],
       [-0.02049982],
       [-0.00548821],
       [ 0.00900162],
       [ 0.00616679],
       [ 0.02203875],
       [ 0.00084814],
       [ 0.00492466]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.00772839], dtype=float32)>]
28:tf.Tensor(0.019072143, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.019064225, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.08214618],
       [-0.00472249],
       [ 0.00034052],
       [-0.02044873],
       [-0.00544109],
       [ 0.00904776],
       [ 0.00621728],
       [ 0.02207652],
       [ 0.00089431],
       [ 0.00497112]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.00763719], dtype=float32)>]
29:tf.Tensor(0.019064225, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Ten

tf.Tensor(0.018801134, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.08011687],
       [-0.00329847],
       [ 0.00185407],
       [-0.01891078],
       [-0.00402947],
       [ 0.01040996],
       [ 0.00770477],
       [ 0.02316593],
       [ 0.00226594],
       [ 0.00634131]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.00492025], dtype=float32)>]
63:tf.Tensor(0.018801134, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.018793551, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.08006297],
       [-0.00326197],
       [ 0.0018928 ],
       [-0.01887089],
       [-0.00399305],
       [ 0.01044449],
       [ 0.00774238],
       [ 0.02319274],
       [ 0.00230098],
       [ 0.00637601]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.00485062], dtype=float32)>]
64:tf.Tensor(0.018793551, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.018785981, s

96:tf.Tensor(0.018554904, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.018547555, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07844043],
       [-0.00220289],
       [ 0.00301514],
       [-0.01769833],
       [-0.00292829],
       [ 0.01143513],
       [ 0.00881869],
       [ 0.0239383 ],
       [ 0.00331468],
       [ 0.00737035]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.00282941], dtype=float32)>]
97:tf.Tensor(0.018547555, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.018540215, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07839557],
       [-0.00217482],
       [ 0.00304484],
       [-0.01766678],
       [-0.00289983],
       [ 0.01146103],
       [ 0.00884674],
       [ 0.02395703],
       [ 0.00334145],
       [ 0.00739631]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.00277582], dtype=float32)>]
98:tf.Tensor(0.018540215

[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07688615],
       [-0.00127477],
       [ 0.00399473],
       [-0.01663722],
       [-0.00197793],
       [ 0.01227702],
       [ 0.00972691],
       [ 0.02451623],
       [ 0.00419549],
       [ 0.00821288]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.00105754], dtype=float32)>]
135:tf.Tensor(0.018272435, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.018265294, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07684903],
       [-0.00125383],
       [ 0.00401676],
       [-0.01661278],
       [-0.00195622],
       [ 0.01229559],
       [ 0.00974684],
       [ 0.02452809],
       [ 0.00421523],
       [ 0.00823143]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.00101758], dtype=float32)>]
136:tf.Tensor(0.018265294, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.018258156, shape=(), dtype=float32)
[<tf.Tensor: shape=(10

[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07555617],
       [-0.00056708],
       [ 0.00473721],
       [-0.01579149],
       [-0.00123449],
       [ 0.01289014],
       [ 0.01038108],
       [ 0.02487436],
       [ 0.00485881],
       [ 0.00882373]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00029407], dtype=float32)>]
174:tf.Tensor(0.017997175, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.0179902, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07552495],
       [-0.00055159],
       [ 0.00475339],
       [-0.01577245],
       [-0.00121795],
       [ 0.01290314],
       [ 0.01039484],
       [ 0.02488102],
       [ 0.00487321],
       [ 0.00883664]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00032365], dtype=float32)>]
175:tf.Tensor(0.0179902, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.017983228, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), 

[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-7.4480750e-02],
       [-6.6735432e-05],
       [ 5.2579148e-03],
       [-1.5159416e-02],
       [-6.9148454e-04],
       [ 1.3296727e-02],
       [ 1.0807861e-02],
       [ 2.5050744e-02],
       [ 5.3200237e-03],
       [ 9.2261788e-03]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00125016], dtype=float32)>]
211:tf.Tensor(0.017741557, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.017734718, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-7.4453734e-02],
       [-5.5097858e-05],
       [ 5.2699633e-03],
       [-1.5144220e-02],
       [-6.7860249e-04],
       [ 1.3305790e-02],
       [ 1.0817260e-02],
       [ 2.5053719e-02],
       [ 5.3306380e-03],
       [ 9.2351055e-03]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.0012724], dtype=float32)>]
212:tf.Tensor(0.017734718, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.0

[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07347099],
       [ 0.00033509],
       [ 0.00567141],
       [-0.01461495],
       [-0.00023674],
       [ 0.01359411],
       [ 0.01111196],
       [ 0.02510935],
       [ 0.005682  ],
       [ 0.00951755]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00201844], dtype=float32)>]
251:tf.Tensor(0.017470539, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.017463831, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07344742],
       [ 0.00034363],
       [ 0.00568013],
       [-0.01460284],
       [-0.00022681],
       [ 0.01360001],
       [ 0.01111786],
       [ 0.0251094 ],
       [ 0.00568957],
       [ 0.00952329]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00203478], dtype=float32)>]
252:tf.Tensor(0.017463831, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.017457126, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 

(100, 1)
(100, 1)
tf.Tensor(0.017204605, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.0725803 ],
       [ 0.00062979],
       [ 0.00596976],
       [-0.01417781],
       [ 0.00011581],
       [ 0.01378222],
       [ 0.01129527],
       [ 0.02506711],
       [ 0.00593876],
       [ 0.00969856]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00258231], dtype=float32)>]
291:tf.Tensor(0.017204605, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.017198017, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07255924],
       [ 0.00063605],
       [ 0.00597603],
       [-0.01416799],
       [ 0.00012357],
       [ 0.0137858 ],
       [ 0.01129861],
       [ 0.02506502],
       [ 0.0059441 ],
       [ 0.00970194]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00259429], dtype=float32)>]
292:tf.Tensor(0.017198017, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Ten

[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07181667],
       [ 0.00083654],
       [ 0.00617442],
       [-0.01383623],
       [ 0.00038059],
       [ 0.01388644],
       [ 0.01138719],
       [ 0.02495882],
       [ 0.00611081],
       [ 0.00979535]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00297819], dtype=float32)>]
329:tf.Tensor(0.0169564, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.016949927, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07179749],
       [ 0.00084119],
       [ 0.00617897],
       [-0.01382803],
       [ 0.0003868 ],
       [ 0.01388839],
       [ 0.01138873],
       [ 0.02495526],
       [ 0.00611458],
       [ 0.0097971 ]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00298711], dtype=float32)>]
330:tf.Tensor(0.016949927, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.016943455, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1)

tf.Tensor(0.016718723, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07113177],
       [ 0.00098689],
       [ 0.00631885],
       [-0.01355528],
       [ 0.00058933],
       [ 0.01393626],
       [ 0.01141977],
       [ 0.02480668],
       [ 0.00622837],
       [ 0.00983755]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00326634], dtype=float32)>]
366:tf.Tensor(0.016718723, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.016712353, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.0711139 ],
       [ 0.00099039],
       [ 0.00632214],
       [-0.01354827],
       [ 0.00059442],
       [ 0.01393703],
       [ 0.01142002],
       [ 0.02480206],
       [ 0.00623099],
       [ 0.00983811]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00327304], dtype=float32)>]
367:tf.Tensor(0.016712353, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.016705984, s

401:tf.Tensor(0.01649741, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.016491137, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07050809],
       [ 0.00109692],
       [ 0.00642027],
       [-0.01331897],
       [ 0.00075725],
       [ 0.01394812],
       [ 0.01141122],
       [ 0.02462604],
       [ 0.00630719],
       [ 0.00984178]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00347734], dtype=float32)>]
402:tf.Tensor(0.016491137, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.016484864, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.07049127],
       [ 0.00109956],
       [ 0.00642263],
       [-0.01331284],
       [ 0.00076151],
       [ 0.01394803],
       [ 0.01141052],
       [ 0.02462066],
       [ 0.00630897],
       [ 0.00984147]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.0034824], dtype=float32)>]
403:tf.Tensor(0.016484864,

[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.06994929],
       [ 0.00117589],
       [ 0.00648914],
       [-0.01312152],
       [ 0.00089145],
       [ 0.01393431],
       [ 0.01137571],
       [ 0.02443361],
       [ 0.00635722],
       [ 0.00982066]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00362891], dtype=float32)>]
436:tf.Tensor(0.01627944, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.016273262, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.06993325],
       [ 0.0011779 ],
       [ 0.00649082],
       [-0.01311604],
       [ 0.00089509],
       [ 0.01393359],
       [ 0.01137432],
       [ 0.02442768],
       [ 0.00635839],
       [ 0.00981973]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00363277], dtype=float32)>]
437:tf.Tensor(0.016273262, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.016267085, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1

(100, 1)
(100, 1)
tf.Tensor(0.016034339, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.06932135],
       [ 0.00124542],
       [ 0.00654487],
       [-0.01291369],
       [ 0.0010262 ],
       [ 0.01389478],
       [ 0.0113085 ],
       [ 0.02418743],
       [ 0.00639322],
       [ 0.00977251]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00376241], dtype=float32)>]
476:tf.Tensor(0.016034339, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Tensor(0.016028265, shape=(), dtype=float32)
[<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.06930602],
       [ 0.0012469 ],
       [ 0.00654597],
       [-0.01290877],
       [ 0.00102931],
       [ 0.01389353],
       [ 0.01130653],
       [ 0.02418105],
       [ 0.00639386],
       [ 0.00977106]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00376525], dtype=float32)>]
477:tf.Tensor(0.016028265, shape=(), dtype=float32)
(100, 1)
(100, 1)
tf.Ten

In [59]:
linear_layer.weights

[<tf.Variable 'linear_5/Variable:0' shape=(10, 5) dtype=float32, numpy=
 array([[ 0.38154775, -0.17255016, -0.13139383, -0.21162176, -0.07607809],
        [ 0.3762259 , -0.08173338, -0.14214642, -0.11427894, -0.12511624],
        [ 0.4319556 , -0.0796601 , -0.07718513, -0.07887186, -0.13466226],
        [ 0.48076516, -0.11210315, -0.06005874, -0.1602532 , -0.06222769],
        [ 0.42028594, -0.1096622 , -0.10928126, -0.13051184, -0.21664451],
        [ 0.40577397, -0.08069967, -0.02025471, -0.10810657, -0.05899183],
        [ 0.47661242, -0.1628666 , -0.10906509, -0.11503927, -0.14784949],
        [ 0.3438376 , -0.17638105, -0.14885348, -0.10512989, -0.06634267],
        [ 0.45067358, -0.04904626, -0.19873412, -0.14366615, -0.06720552],
        [ 0.39997646, -0.14502122, -0.13020997, -0.15987176, -0.17147659]],
       dtype=float32)>,
 <tf.Variable 'linear_5/Variable:0' shape=(5,) dtype=float32, numpy=
 array([ 0.77334636, -0.24437654, -0.18338907, -0.25161073, -0.26894087],
       dty

In [60]:
linear_layer(X)

<tf.Tensor: shape=(100, 5), dtype=float32, numpy=
array([[ 3.034051  , -0.8944886 , -0.702909  , -0.9100907 , -0.91471446],
       [ 2.672649  , -0.7518977 , -0.6032771 , -0.8623564 , -0.7870396 ],
       [ 2.6352067 , -0.79033923, -0.6407495 , -0.8783432 , -0.8192817 ],
       [ 2.756093  , -0.80055165, -0.74506974, -0.8831645 , -0.76203316],
       [ 2.9205348 , -0.7598562 , -0.7051387 , -0.93502796, -0.805391  ],
       [ 3.9921074 , -1.1441263 , -1.0629559 , -1.2652736 , -1.1164141 ],
       [ 3.1529875 , -0.9368951 , -0.7760275 , -0.99894464, -0.9972597 ],
       [ 2.7661839 , -0.82357496, -0.6635958 , -0.8873267 , -0.81625915],
       [ 3.1256547 , -0.85570645, -0.8168875 , -0.97133875, -0.83389294],
       [ 2.9122365 , -0.86329085, -0.8987118 , -0.93748   , -0.9110836 ],
       [ 3.0623174 , -0.8757689 , -0.8222541 , -0.9788867 , -0.93330795],
       [ 2.7572215 , -0.8300353 , -0.79856026, -0.93213725, -0.7934496 ],
       [ 3.466855  , -1.0603781 , -0.8761009 , -1.1164559 , -0

In [74]:
ll.weights

[<tf.Variable 'linear_7/Variable:0' shape=(10, 1) dtype=float32, numpy=
 array([[ 0.07310411],
        [ 0.03043605],
        [ 0.04264448],
        [-0.03265332],
        [ 0.06596532],
        [ 0.06827129],
        [-0.02262687],
        [-0.00325235],
        [ 0.06446396],
        [ 0.00166935]], dtype=float32)>,
 <tf.Variable 'linear_7/Variable:0' shape=(1,) dtype=float32, numpy=array([0.1263317], dtype=float32)>]

In [75]:
ll(X)

<tf.Tensor: shape=(100, 1), dtype=float32, numpy=
array([[0.24437833],
       [0.3312772 ],
       [0.3059557 ],
       [0.21893546],
       [0.29900903],
       [0.35676956],
       [0.28232408],
       [0.25822824],
       [0.35186645],
       [0.2755518 ],
       [0.29337156],
       [0.3025197 ],
       [0.30708334],
       [0.2683381 ],
       [0.27881792],
       [0.23599215],
       [0.30424803],
       [0.3368461 ],
       [0.2257308 ],
       [0.3137878 ],
       [0.22305349],
       [0.25933236],
       [0.25119352],
       [0.3258852 ],
       [0.23904541],
       [0.27603632],
       [0.34064767],
       [0.2659328 ],
       [0.24248712],
       [0.2556167 ],
       [0.22390115],
       [0.25944877],
       [0.2188208 ],
       [0.3380752 ],
       [0.29707026],
       [0.27538574],
       [0.27760804],
       [0.20676562],
       [0.2561078 ],
       [0.2963975 ],
       [0.17675146],
       [0.24136415],
       [0.2944481 ],
       [0.28884104],
       [0.2942977 ],
     

In [76]:
X

array([[2.16516275e-01, 4.52325155e-01, 5.32777127e-01, 7.22560264e-01,
        9.56288209e-01, 7.03761984e-01, 9.58564533e-01, 6.59447714e-01,
        2.84955134e-02, 1.16175147e-01],
       [7.26017653e-01, 3.50983721e-02, 8.15696602e-01, 4.59869560e-01,
        8.23229475e-01, 9.22358909e-01, 4.17603371e-02, 2.04199559e-01,
        2.30529745e-01, 3.03476404e-01],
       [8.46697650e-01, 5.24913284e-01, 2.60050645e-01, 2.06690676e-01,
        7.43119534e-01, 8.04232597e-01, 5.44110959e-01, 6.73325241e-02,
        8.22001588e-02, 4.28605801e-01],
       [3.89190080e-01, 3.61369545e-01, 6.07727728e-01, 6.87158215e-01,
        5.88220117e-02, 2.02409358e-01, 4.65979095e-01, 5.93445941e-01,
        6.72085876e-01, 6.73879662e-01],
       [3.86457209e-01, 2.74943189e-01, 6.57735149e-01, 7.50114510e-01,
        3.59624798e-01, 8.72615156e-01, 1.47206923e-01, 3.91243853e-02,
        7.97298242e-01, 7.58520632e-01],
       [7.42243237e-01, 6.03738041e-01, 9.09159803e-01, 7.19831311e-01,
   